# Generated by Django 2.1.3 on 2022-06-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindata',
            old_name='label',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
