# Generated by Django 2.1.3 on 2022-06-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220623_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='info',
            field=models.TextField(),
        ),
    ]
