# Generated by Django 2.1.3 on 2022-06-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220623_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='image_url',
            field=models.TextField(),
        ),
    ]
