# Generated by Django 2.1.3 on 2022-06-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220623_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adds', models.CharField(max_length=250)),
                ('contacts', models.CharField(max_length=250)),
            ],
        ),
    ]
