# Generated by Django 2.1.3 on 2022-06-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutusdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusdata',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
